In [241]:
import pandas as pd

In [242]:
df_2022 = pd.read_excel('2022.xlsx')
df_2022

,ID,Start time,Completion time,Email,Name,Last modified time,Rollno,Full Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship
0,93,2023-10-09 19:49:42,2023-10-09 19:56:10,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva [CB.EN.U4CSE20108],NaN,CB.EN.U4CSE20108,N Apoorva,CSE B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
1,34,2023-09-24 20:59:50,2023-09-24 21:04:40,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran [CB.EN.U4CSE20121],NaN,CB.EN.U4CSE20121,Gadde Uday Kiran,CSE B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
2,5,2023-09-24 09:13:59,2023-09-24 09:21:38,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy [CB.EN.U4CSE20153],NaN,CB.EN.U4CSE20153,G Rama Vamsidhar Reddy,CSE B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
3,45,2023-09-25 13:25:46,2023-09-25 13:36:00,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA [CB.EN.U4CSE20466],NaN,CB.EN.U4CSE20466,T Subhash Gupta,CSE E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
4,98,2023-10-17 10:05:29,2023-10-17 10:13:22,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan [CB.EN.U4CSE20640],NaN,CB.EN.U4CSE20640,Nallabantu Sri Charan,CSE F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,35,2023-09-25 08:56:22,2023-09-25 09:00:18,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R [CB.EN.U4CSE20615],NaN,CB.EN.U4CSE20615,Dharshita R,CSE F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
125,52,2023-09-25 17:50:44,2023-09-25 17:54:31,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar [CB.EN.U4CSE20425],NaN,CB.EN.U4CSE20425,Jayandar S,CSE E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
126,116,2023-10-27 15:51:20,2023-10-27 15:52:33,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha [CB.EN.U4CSE20051],NaN,CB.EN.U4CSE20051,Preethi Prabha,CSE A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
127,85,2023-10-06 17:05:50,2023-10-06 17:07:38,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya [CB.EN.U4CSE20109],NaN,CB.EN.U4CSE20109,Arvapalli Alekhya,CSE B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
128,106,2023-10-20 10:11:43,2023-10-20 10:13:19,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K [CB.EN.U4CSE20348],NaN,CB.EN.U4CSE20348,Priyanka Karunakaran,CSE D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR

In [243]:
df_2022.columns

Index(['ID', 'Start time', 'Completion time', 'Email', 'Name',
       'Last modified time', 'Rollno', 'Full Name', 'Section', 'Company',
       'Interview date and Time', 'Tentative Location', 'Role/Position',
       'Company CTC',
       'High Resolution Professional Passport Size Photo with white background',
       'Company offer is', 'Placement /Internship'],
      dtype='object')

In [244]:
df_2022.drop(['ID', 'Start time', 'Completion time', 'Last modified time'], axis=1, inplace=True)
df_2022

,Email,Name,Rollno,Full Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva [CB.EN.U4CSE20108],CB.EN.U4CSE20108,N Apoorva,CSE B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran [CB.EN.U4CSE20121],CB.EN.U4CSE20121,Gadde Uday Kiran,CSE B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy [CB.EN.U4CSE20153],CB.EN.U4CSE20153,G Rama Vamsidhar Reddy,CSE B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA [CB.EN.U4CSE20466],CB.EN.U4CSE20466,T Subhash Gupta,CSE E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan [CB.EN.U4CSE20640],CB.EN.U4CSE20640,Nallabantu Sri Charan,CSE F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R [CB.EN.U4CSE20615],CB.EN.U4CSE20615,Dharshita R,CSE F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar [CB.EN.U4CSE20425],CB.EN.U4CSE20425,Jayandar S,CSE E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha [CB.EN.U4CSE20051],CB.EN.U4CSE20051,Preethi Prabha,CSE A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya [CB.EN.U4CSE20109],CB.EN.U4CSE20109,Arvapalli Alekhya,CSE B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K [CB.EN.U4CSE20348],CB.EN.U4CSE20348,Priyanka Karunakaran,CSE D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR

In [245]:
df_2022['Name'] = df_2022['Name'].str.replace(r"\[.*\]$", "")
df_2022.drop(['Full Name'], axis=1, inplace=True)
df_2022

/var/folders/79/k0pjppyx72xcfj5m7k0_zjqm0000gp/T/ipykernel_10754/304725831.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_2022['Name'] = df_2022['Name'].str.replace(r"\[.*\]$", "")

,Email,Name,Rollno,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,CB.EN.U4CSE20108,CSE B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,CB.EN.U4CSE20121,CSE B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,CB.EN.U4CSE20153,CSE B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,CB.EN.U4CSE20466,CSE E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,CB.EN.U4CSE20640,CSE F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,CB.EN.U4CSE20615,CSE F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,CB.EN.U4CSE20425,CSE E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,CB.EN.U4CSE20051,CSE A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,CB.EN.U4CSE20109,CSE B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,CB.EN.U4CSE20348,CSE D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR

In [246]:
df_2022.drop(['Rollno'], axis=1, inplace=True)
df_2022

,Email,Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,CSE B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,CSE B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,CSE B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,CSE E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,CSE F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,CSE F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,CSE E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,CSE A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,CSE B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,CSE D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR

In [247]:
# From email ID extract the content before @, upper case it and add it as rollNo
df_2022['rollNumber'] = df_2022['Email'].str.split('@').str[0].str.upper()
df_2022

,Email,Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship,rollNumber
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,CSE B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20108
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,CSE B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20121
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,CSE B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20153
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,CSE E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20466
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,CSE F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20640
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,CSE F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20615
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,CSE E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20425
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,CSE A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20051
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,CSE B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20109
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,CSE D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20348

In [248]:
df_2022['Section'].value_counts()

CSE F    29
CSE C    24
CSE A    21
CSE E    19
CSE B    18
CSE D    18
Name: Section, dtype: int64

In [249]:
# Take last character alone from section
df_2022['Section'] = df_2022['Section'].str[-1]
df_2022

,Email,Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship,rollNumber
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20108
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20121
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20153
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20466
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20640
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20615
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20425
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20051
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20109
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20348

In [250]:
df_2022['Company'].unique()

array(['ABOBE ', 'ACCENTURE', 'ACCENTURE ', 'ALSTOM', 'AMADEUS LABS',
       'APPVIEWX', 'ARCADIA', 'BNP PARIBAS', 'BNP PARIBAS ',
       'BNP PARIBAS ISPL', 'BNY MELLON', 'BOSCH',
       'BOSCH GLOBAL SOFTWARE SOLUTIONS',
       'BOSCH GLOBAL SOFTWARE TECHNOLOGIES PVT LTD',
       'CAMS(COMPUTER AGE MANAGEMENT SEVICES)', 'CATERPILLAR',
       'CATERPILLAR INC', 'CISCO', 'COMVIVA', 'E2OPEN',
       'FIDELITY INVESTMENTS', 'GE DIGITAL', 'GE HEALTHCARE ',
       'GE-GENERAL ELECTRIC (AVIATION)', 'GENPACT ', 'HONEYWELL', 'IBM',
       'IBM ', 'INTUIT', 'LATENT VIEW', 'LATENT VIEW ANALYTICS',
       'MICROCHIP', 'MICROSOFT', 'NOKIA', 'ORACLE', 'ORACLE ',
       'PROVIDENCE INDIA', 'PWC', 'PWC ', 'SAHAJ SOFTWARE ',
       'SAMSUNG ELECTRO MECHANICS SOFTWARE', 'SAMSUNG ELECTRO-MECHANICS',
       'SAP LABS', 'SAP LABS INDIA', 'SCHLUMBERGER (SLB)',
       'SCHNEIDER ELECTRIC', 'SIGNIFY INNOVATION LABS',
       'SIGNIFY INNOVATIONS', 'SLB (SCHLUMBERGER)', 'TALLY SOLUTIONS',
       'TALLY SOLUTIONS ', 'TATA COMMUNICATIONS ', 'TOSHIBA',
       'TREDENCE ANALYTICS', 'TREDENCE ANALYTICS ', 'TRIANZ', 'TRIANZ ',
       'VALEO', 'VANENBURG ', 'VERIZON', 'VISTEON CORPORATION', 'VOLVO'],
      dtype=object)

In [251]:
df_2022['Company offer is'].unique()

array(['Placement', 'Placement/Internship', 'Internship'], dtype=object)

In [252]:
df_2022['Company offer is'].value_counts()

Placement               67
Placement/Internship    48
Internship              14
Name: Company offer is, dtype: int64

In [253]:
df_2022[df_2022['Company offer is'] == 'Placement/Internship']['Role/Position'].unique()

array(['Software Engineer (SWE)', 'SDE-1',
       'Software development engineer ',
       'Software Engineer - Development', 'Software Engineer ',
       'Product Engineer', 'Software Developer ', 'SOFTWARE ENGINEER',
       'Software Engineer', 'Associate Engineer ',
       'Associate Software Engineer', 'Business System Analyst',
       'Digital Technology Intern/Software Engineering Specialist',
       'Not informed', 'Protocol System Test Engineer',
       'Associate Software Engineer / Associate Application Developer ',
       'Associate software engineer',
       'Associate Software Engineer / Associate Application Developer',
       'GBU', 'Software Development Engineer', 'TC',
       'Technical consultant ', 'Technology consultant ',
       'Technical consultant', 'Solutions consultant',
       'Associate Software Developer', 'Software Developer',
       'Graduate Engineer Trainee,R&D ', 'R&D', 'IT TECHNICAL ROLE',
       'IT Technical Engineer', 'Not assigned',
       'Trainee- Software Engineer/DevOps Engineer', 'software engineer',
       'SDE'], dtype=object)

In [254]:
df_2022['Company offer is'].replace({'Placement/Internship': 'PPO'}, inplace=True)
df_2022

,Email,Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,Placement /Internship,rollNumber
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20108
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20121
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20153
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20466
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20640
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20615
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20425
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20051
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20109
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,CIR,CB.EN.U4CSE20348

In [255]:
df_2022['Company offer is'].value_counts()

Placement     67
PPO           48
Internship    14
Name: Company offer is, dtype: int64

In [256]:
df_2022['Placement /Internship'].value_counts()

CIR             128
not thru CIR      1
Name: Placement /Internship, dtype: int64

In [257]:
df_2022['Placement /Internship'].replace({'CIR': '1', 'not thru CIR': '0'}, inplace=True)
df_2022['Placement /Internship'].value_counts()

1    128
0      1
Name: Placement /Internship, dtype: int64

In [258]:
# Rename column
df_2022.rename(columns={'Placement /Internship': 'isOnCampus'}, inplace=True)
df_2022

,Email,Name,Section,Company,Interview date and Time,Tentative Location,Role/Position,Company CTC,High Resolution Professional Passport Size Photo with white background,Company offer is,isOnCampus,rollNumber
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20108
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20121
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20153
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20466
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20640
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20615
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20425
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20051
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20109
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20348

In [259]:
df_2022.rename(
    columns={
        'Email': "studentEmail",
        'Name': "studentName",
        'Section': 'studentSection',
        'Company': 'companyName',
        'Interview date and Time': 'placementDate',
        'Tentative Location': 'jobLocation',
        'Role/Position': 'jobRole',
        'Company CTC': 'ctc',
        'Company offer is': 'isIntern/isPPO',
        'rollNumber': 'studentRollNo'
    },
    inplace=True
)
df_2022

,studentEmail,studentName,studentSection,companyName,placementDate,jobLocation,jobRole,ctc,High Resolution Professional Passport Size Photo with white background,isIntern/isPPO,isOnCampus,studentRollNo
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20108
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20121
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20153
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20466
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20640
...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20615
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20425
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20051
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20109
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,Placement,1,CB.EN.U4CSE20348

In [260]:
# Split isIntern/isPPO into two columns isIntern and isPPO
df_2022['isIntern'] = df_2022['isIntern/isPPO']
df_2022['isPPO'] = df_2022['isIntern/isPPO']

df_2022.drop(['isIntern/isPPO'], axis=1, inplace=True)
df_2022

,studentEmail,studentName,studentSection,companyName,placementDate,jobLocation,jobRole,ctc,High Resolution Professional Passport Size Photo with white background,isOnCampus,studentRollNo,isIntern,isPPO
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20108,Placement,Placement
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20121,Placement,Placement
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20153,Placement,Placement
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20466,Placement,Placement
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20640,Placement,Placement
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20615,Placement,Placement
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20425,Placement,Placement
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20051,Placement,Placement
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20109,Placement,Placement
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20348,Placement,Placement

In [261]:
df_2022['isIntern'].value_counts()

Placement     67
PPO           48
Internship    14
Name: isIntern, dtype: int64

In [262]:
df_2022['isIntern'].replace({'Placement': '0', 'Internship': '1', 'PPO': '0'}, inplace=True)
df_2022['isIntern'].value_counts()

0    115
1     14
Name: isIntern, dtype: int64

In [263]:
df_2022['isPPO'].value_counts()

Placement     67
PPO           48
Internship    14
Name: isPPO, dtype: int64

In [264]:
df_2022['isPPO'].replace({'Placement': '0', 'Internship': '0', 'PPO': '1'}, inplace=True)
df_2022['isPPO'].value_counts()

0    81
1    48
Name: isPPO, dtype: int64

In [265]:
df_2022.columns

Index(['studentEmail', 'studentName', 'studentSection', 'companyName',
       'placementDate', 'jobLocation', 'jobRole', 'ctc',
       'High Resolution Professional Passport Size Photo with white background',
       'isOnCampus', 'studentRollNo', 'isIntern', 'isPPO'],
      dtype='object')

In [266]:
df_2022['isGirlsDrive'] = '0'
df_2022

,studentEmail,studentName,studentSection,companyName,placementDate,jobLocation,jobRole,ctc,High Resolution Professional Passport Size Photo with white background,isOnCampus,studentRollNo,isIntern,isPPO,isGirlsDrive
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20108,0,0,0
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20121,0,0,0
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20153,0,0,0
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20466,0,0,0
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20640,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20615,0,0,0
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20425,0,0,0
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20051,0,0,0
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20109,0,0,0
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,https://amritavishwavidyapeetham-my.sharepoint...,1,CB.EN.U4CSE20348,0,0,0

In [267]:
df_2022['isHigherStudies'] = '0'
df_2022['studentDept'] = 'CSE'
df_2022['studentBatch'] = '2024'
df_2022['isPlaced'] = '1'
df_2022['studentPassword'] = df_2022['studentEmail'] + '_' + df_2022['studentSection']
df_2022.drop(['High Resolution Professional Passport Size Photo with white background'], axis=1, inplace=True)
df_2022

,studentEmail,studentName,studentSection,companyName,placementDate,jobLocation,jobRole,ctc,isOnCampus,studentRollNo,isIntern,isPPO,isGirlsDrive,isHigherStudies,studentDept,studentBatch,isPlaced,studentPassword
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,ABOBE,2022-10-17,Bengaluru,Technical Consultant,10.71,1,CB.EN.U4CSE20108,0,0,0,0,CSE,2024,1,cb.en.u4cse20108@cb.students.amrita.edu_B
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,ACCENTURE,2022-11-11,Bangalore,Advanced Application Engineering Analyst,"11,89,000",1,CB.EN.U4CSE20121,0,0,0,0,CSE,2024,1,cb.en.u4cse20121@cb.students.amrita.edu_B
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,ACCENTURE,2022-11-11,Banglore,Advanced App Engineering Analyst,"11,89,000",1,CB.EN.U4CSE20153,0,0,0,0,CSE,2024,1,cb.en.u4cse20153@cb.students.amrita.edu_B
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,ACCENTURE,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,"11,89,000",1,CB.EN.U4CSE20466,0,0,0,0,CSE,2024,1,cb.en.u4cse20466@cb.students.amrita.edu_E
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,ACCENTURE,2023-08-24,Coimbatore,Advanced App Engineering Analyst,"11,89,000",1,CB.EN.U4CSE20640,0,0,0,0,CSE,2024,1,cb.en.u4cse20640@cb.students.amrita.edu_F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,VERIZON,2023-09-06,Chennai,Software Engineer,"9,74,000",1,CB.EN.U4CSE20615,0,0,0,0,CSE,2024,1,cb.en.u4cse20615@cb.students.amrita.edu_F
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,VISTEON CORPORATION,2023-08-25,Coimbatore,Software Engineer,7,1,CB.EN.U4CSE20425,0,0,0,0,CSE,2024,1,cb.en.u4cse20425@cb.students.amrita.edu_E
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5,1,CB.EN.U4CSE20051,0,0,0,0,CSE,2024,1,cb.en.u4cse20051@cb.students.amrita.edu_A
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,VOLVO,2023-09-15,Bangalore,Associate Engineer,7.5 LPA,1,CB.EN.U4CSE20109,0,0,0,0,CSE,2024,1,cb.en.u4cse20109@cb.students.amrita.edu_B
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,VOLVO,2023-09-25,Bangalore,Associate Engineer,7.5,1,CB.EN.U4CSE20348,0,0,0,0,CSE,2024,1,cb.en.u4cse20348@cb.students.amrita.edu_D

In [268]:
# Preprocess 'ctc'

df_2022['ctc'].unique()

# df_2022.to_csv('2024.csv', index=False)

array([10.71, '11,89,000', 680000, '12,62,217', 1200000, 1500000, 50000,
       2164308, 700000, 600000, 1223000, 1600000, 650000, 800000, 1737088,
       1511088, 1511089, 40000, 1100000, 'Not discussed ',
       '30,000 per month', 450000, 4400000, 850000, 1075000, 4875000,
       820000, 1918300, '19.2 LPA', 19.2, '19,18,300', '19.1L',
       '19,20,000', '19.18L', '19.1 LPA', '20 LPA', 8.9, 9, '8.99 LPA',
       '8.9L ', '9 LPA', 13.07, '35k per month', '7-12', 24.5, 24, 15,
       '12LPA', 12, '12 LPA', '10.2 LAKHS', '10.20 LPA', '10,20,000',
       10.2, '19,73,626', '11,30,000 per annum', '11,30,000', 7.5,
       '9 lakhs', 10, '10L', '10 LPA', 1000000, '10LPA', '9L', '5lpa',
       '15K/month stipend', nan, '7,00,000', 9.74, 974000, 9.72,
       '9,74,000', 7, '7.5 LPA'], dtype=object)

In [269]:
df_2022['companyName'] = df_2022['companyName'].str.upper().str.strip()
df_2022['companyName'].unique()

array(['ABOBE', 'ACCENTURE', 'ALSTOM', 'AMADEUS LABS', 'APPVIEWX',
       'ARCADIA', 'BNP PARIBAS', 'BNP PARIBAS ISPL', 'BNY MELLON',
       'BOSCH', 'BOSCH GLOBAL SOFTWARE SOLUTIONS',
       'BOSCH GLOBAL SOFTWARE TECHNOLOGIES PVT LTD',
       'CAMS(COMPUTER AGE MANAGEMENT SEVICES)', 'CATERPILLAR',
       'CATERPILLAR INC', 'CISCO', 'COMVIVA', 'E2OPEN',
       'FIDELITY INVESTMENTS', 'GE DIGITAL', 'GE HEALTHCARE',
       'GE-GENERAL ELECTRIC (AVIATION)', 'GENPACT', 'HONEYWELL', 'IBM',
       'INTUIT', 'LATENT VIEW', 'LATENT VIEW ANALYTICS', 'MICROCHIP',
       'MICROSOFT', 'NOKIA', 'ORACLE', 'PROVIDENCE INDIA', 'PWC',
       'SAHAJ SOFTWARE', 'SAMSUNG ELECTRO MECHANICS SOFTWARE',
       'SAMSUNG ELECTRO-MECHANICS', 'SAP LABS', 'SAP LABS INDIA',
       'SCHLUMBERGER (SLB)', 'SCHNEIDER ELECTRIC',
       'SIGNIFY INNOVATION LABS', 'SIGNIFY INNOVATIONS',
       'SLB (SCHLUMBERGER)', 'TALLY SOLUTIONS', 'TATA COMMUNICATIONS',
       'TOSHIBA', 'TREDENCE ANALYTICS', 'TRIANZ', 'VALEO', 'VANENBURG',
       'VERIZON', 'VISTEON CORPORATION', 'VOLVO'], dtype=object)

In [270]:
# Replace 'SIGNIFY INNOVATIONS' with 'SIGNIFY INNOVATION LABS'
df_2022['companyName'].replace({
    'SIGNIFY INNOVATIONS': 'SIGNIFY INNOVATION LABS',
    'SLB (SCHLUMBERGER)': 'SCHLUMBERGER',
    'SCHLUMBERGER (SLB)': 'SCHLUMBERGER',
    'SAP LABS INDIA': 'SAP LABS',
    'SAMSUNG ELECTRO MECHANICS SOFTWARE': 'SAMSUNG ELECTRO-MECHANICS',
    'LATENT VIEW': 'LATENT VIEW ANALYTICS',
    'CATERPILLAR INC': 'CATERPILLAR',
    'BOSCH GLOBAL SOFTWARE TECHNOLOGIES PVT LTD': 'BOSCH',
    'BOSCH GLOBAL SOFTWARE SOLUTIONS': 'BOSCH',
    'GE-GENERAL ELECTRIC (AVIATION)': 'GE',
    'GE HEALTHCARE': 'GE',
    'GE DIGITAL': 'GE',
    }, inplace=True)

df_2022['companyName'].value_counts().sort_index(ascending=False)

VOLVO                                     3
VISTEON CORPORATION                       1
VERIZON                                   8
VANENBURG                                 1
VALEO                                     3
TRIANZ                                   15
TREDENCE ANALYTICS                        2
TOSHIBA                                   1
TATA COMMUNICATIONS                       1
TALLY SOLUTIONS                           2
SIGNIFY INNOVATION LABS                   5
SCHNEIDER ELECTRIC                        4
SCHLUMBERGER                              2
SAP LABS                                  2
SAMSUNG ELECTRO-MECHANICS                 2
SAHAJ SOFTWARE                            1
PWC                                       9
PROVIDENCE INDIA                          2
ORACLE                                    8
NOKIA                                     1
MICROSOFT                                 1
MICROCHIP                                 1
LATENT VIEW ANALYTICS                     5
INTUIT                                    1
IBM                                       3
HONEYWELL                                 1
GENPACT                                   2
GE                                        4
FIDELITY INVESTMENTS                      1
E2OPEN                                    2
COMVIVA                                   4
CISCO                                     1
CATERPILLAR                               3
CAMS(COMPUTER AGE MANAGEMENT SEVICES)     1
BOSCH                                     3
BNY MELLON                                3
BNP PARIBAS ISPL                          1
BNP PARIBAS                               2
ARCADIA                                   2
APPVIEWX                                  4
AMADEUS LABS                              4
ALSTOM                                    1
ACCENTURE                                 5
ABOBE                                     1
Name: companyName, dtype: int64

In [271]:
company_data = pd.read_csv('companyData.csv')
company_data

                companyName
0                    CISCO
1           CISCO-2nd Drive
2                    INTUIT
3                    INTUIT
4             ROOT QUOTIENT
..                      ...
69                  TARGET
70  L&T Technology services
71                  Toshiba
72                   CERNER
73                     NPCI

[74 rows x 1 columns]

In [272]:
company_data['companyName'] = company_data['companyName'].str.upper().str.strip()
companyList = company_data['companyName'].unique()
companyList.sort()

In [273]:
companyList

array(['ALSTOM', 'AMAZON', 'APPVIEWX (R & D)',
       'APPVIEWX (SOFTWARE ENGINEER)', 'ARISTA', 'ATLASSIAN',
       'CAPEGEMINI', 'CATTERPILLAR', 'CERNER', 'CHARGEBEE', 'CISCO',
       'CISCO-2ND DRIVE', 'COGNIZANT-GENC', 'COGNIZANT-GENC ELEVATE',
       'COGNIZANT-GENC NEXT', 'DATAFOUNDRY.AI', 'EPIKINDIFI', 'EY INDIA',
       'FIDILITY', 'FRACTAL ANALYSIS', 'HASHED IN', 'HYPERVERGE', 'IBM',
       'IBM-CIO', 'INCREFF(DEVOPS)', 'INCREFF(QA ENGINEER)',
       'INCREFF(SDE)', 'INFOSYS(DSE)', 'INFOSYS(SE)', 'INTUIT',
       'KLA TENCOR', 'KPMG', 'L&T TECHNOLOGY SERVICES',
       'LISTER TECHNOLOGIES', 'MCKINSEY', 'MERCEDES BENZ- TRUCK',
       'MERECEDES BENZ-CARS', 'MICRO FOCUS', 'MICROSOFT', 'NIELSENIQ',
       'NPCI', 'OPTUM', 'OPTUM(GIRLS DRIVE)', 'ORACLE', 'PAY U',
       'PROVIDENCE GLOBAL', 'PWC', 'RAZOR PAY', 'ROBERT BOSCH',
       'ROOT QUOTIENT', 'SAHAJ', 'SAP LABS', 'SCHNEIDER ELECTRIC',
       'SS&C EZE', 'TALLY SOLUTIONS', 'TARGET', 'TCS-DIGITAL',
       'TCS-NINJA', 'THE MATH COMPANY', 'TIGER ANALYTICS', 'TOSHIBA',
       'VANENBURG', 'VERIZON', 'VERSA NETWORKS', 'VM WARE', 'WIPRO',
       'WONKSKNOW TECHNOLOGIES', 'ZOOM RX', 'ZSCALER', '[24]7.AI'],
      dtype=object)

In [274]:
company_data.replace({
    'APPVIEWX (R & D)': 'APPVIEWX',
    'APPVIEWX (SOFTWARE ENGINEER)': 'APPVIEWX',
    'CISCO-2ND DRIVE': 'CISCO',
    'COGNIZANT-GENC ELEVATE': 'COGNIZANT',
    'COGNIZANT-GENC NEXT': 'COGNIZANT',
    'COGNIZANT-GENC': 'COGNIZANT',
    'EY INDIA': 'EY',
    'IBM-CIO': 'IBM',
    'INCREFF(DEVOPS)': 'INCREFF',
    'INCREFF(QA ENGINEER)': 'INCREFF',
    'INCREFF(SDE)': 'INCREFF',
    'INFOSYS(DSE)': 'INFOSYS',
    'INFOSYS(SE)': 'INFOSYS',
    'L&T TECHNOLOGY SERVICES': 'L&T',
    'MERCEDES BENZ- TRUCK': 'MERCEDES BENZ',
    'MERECEDES BENZ-CARS': 'MERCEDES BENZ',
    'OPTUM(GIRLS DRIVE)': 'OPTUM',
    'TCS-DIGITAL': 'TCS',
    'TCS-NINJA': 'TCS',
}, inplace=True)

companyList = company_data['companyName'].unique()
companyList.sort()
companyList

array(['ALSTOM', 'AMAZON', 'APPVIEWX', 'ARISTA', 'ATLASSIAN',
       'CAPEGEMINI', 'CATTERPILLAR', 'CERNER', 'CHARGEBEE', 'CISCO',
       'COGNIZANT', 'DATAFOUNDRY.AI', 'EPIKINDIFI', 'EY', 'FIDILITY',
       'FRACTAL ANALYSIS', 'HASHED IN', 'HYPERVERGE', 'IBM', 'INCREFF',
       'INFOSYS', 'INTUIT', 'KLA TENCOR', 'KPMG', 'L&T',
       'LISTER TECHNOLOGIES', 'MCKINSEY', 'MERCEDES BENZ', 'MICRO FOCUS',
       'MICROSOFT', 'NIELSENIQ', 'NPCI', 'OPTUM', 'ORACLE', 'PAY U',
       'PROVIDENCE GLOBAL', 'PWC', 'RAZOR PAY', 'ROBERT BOSCH',
       'ROOT QUOTIENT', 'SAHAJ', 'SAP LABS', 'SCHNEIDER ELECTRIC',
       'SS&C EZE', 'TALLY SOLUTIONS', 'TARGET', 'TCS', 'THE MATH COMPANY',
       'TIGER ANALYTICS', 'TOSHIBA', 'VANENBURG', 'VERIZON',
       'VERSA NETWORKS', 'VM WARE', 'WIPRO', 'WONKSKNOW TECHNOLOGIES',
       'ZOOM RX', 'ZSCALER', '[24]7.AI'], dtype=object)

In [275]:
companyList2 = df_2022['companyName'].unique()
companyList2.sort()
companyList2

array(['ABOBE', 'ACCENTURE', 'ALSTOM', 'AMADEUS LABS', 'APPVIEWX',
       'ARCADIA', 'BNP PARIBAS', 'BNP PARIBAS ISPL', 'BNY MELLON',
       'BOSCH', 'CAMS(COMPUTER AGE MANAGEMENT SEVICES)', 'CATERPILLAR',
       'CISCO', 'COMVIVA', 'E2OPEN', 'FIDELITY INVESTMENTS', 'GE',
       'GENPACT', 'HONEYWELL', 'IBM', 'INTUIT', 'LATENT VIEW ANALYTICS',
       'MICROCHIP', 'MICROSOFT', 'NOKIA', 'ORACLE', 'PROVIDENCE INDIA',
       'PWC', 'SAHAJ SOFTWARE', 'SAMSUNG ELECTRO-MECHANICS', 'SAP LABS',
       'SCHLUMBERGER', 'SCHNEIDER ELECTRIC', 'SIGNIFY INNOVATION LABS',
       'TALLY SOLUTIONS', 'TATA COMMUNICATIONS', 'TOSHIBA',
       'TREDENCE ANALYTICS', 'TRIANZ', 'VALEO', 'VANENBURG', 'VERIZON',
       'VISTEON CORPORATION', 'VOLVO'], dtype=object)

In [276]:
finalSet = list(set(list(companyList) + list(companyList2)))
finalSet.sort()
finalSet.remove('CATTERPILLAR')
finalSet.remove('FIDELITY INVESTMENTS')
finalSet.remove('PROVIDENCE GLOBAL')
finalSet.remove('PROVIDENCE INDIA')
finalSet.append('PROVIDENCE')
finalSet.remove('SAHAJ SOFTWARE')
finalSet.sort()
finalSet

['ABOBE',
 'ACCENTURE',
 'ALSTOM',
 'AMADEUS LABS',
 'AMAZON',
 'APPVIEWX',
 'ARCADIA',
 'ARISTA',
 'ATLASSIAN',
 'BNP PARIBAS',
 'BNP PARIBAS ISPL',
 'BNY MELLON',
 'BOSCH',
 'CAMS(COMPUTER AGE MANAGEMENT SEVICES)',
 'CAPEGEMINI',
 'CATERPILLAR',
 'CERNER',
 'CHARGEBEE',
 'CISCO',
 'COGNIZANT',
 'COMVIVA',
 'DATAFOUNDRY.AI',
 'E2OPEN',
 'EPIKINDIFI',
 'EY',
 'FIDILITY',
 'FRACTAL ANALYSIS',
 'GE',
 'GENPACT',
 'HASHED IN',
 'HONEYWELL',
 'HYPERVERGE',
 'IBM',
 'INCREFF',
 'INFOSYS',
 'INTUIT',
 'KLA TENCOR',
 'KPMG',
 'L&T',
 'LATENT VIEW ANALYTICS',
 'LISTER TECHNOLOGIES',
 'MCKINSEY',
 'MERCEDES BENZ',
 'MICRO FOCUS',
 'MICROCHIP',
 'MICROSOFT',
 'NIELSENIQ',
 'NOKIA',
 'NPCI',
 'OPTUM',
 'ORACLE',
 'PAY U',
 'PROVIDENCE',
 'PWC',
 'RAZOR PAY',
 'ROBERT BOSCH',
 'ROOT QUOTIENT',
 'SAHAJ',
 'SAMSUNG ELECTRO-MECHANICS',
 'SAP LABS',
 'SCHLUMBERGER',
 'SCHNEIDER ELECTRIC',
 'SIGNIFY INNOVATION LABS',
 'SS&C EZE',
 'TALLY SOLUTIONS',
 'TARGET',
 'TATA COMMUNICATIONS',
 'TCS',
 'THE MATH COMPANY',
 'TIGER ANALYTICS',
 'TOSHIBA',
 'TREDENCE ANALYTICS',
 'TRIANZ',
 'VALEO',
 'VANENBURG',
 'VERIZON',
 'VERSA NETWORKS',
 'VISTEON CORPORATION',
 'VM WARE',
 'VOLVO',
 'WIPRO',
 'WONKSKNOW TECHNOLOGIES',
 'ZOOM RX',
 'ZSCALER',
 '[24]7.AI']

In [277]:
finalCompanyDf = pd.DataFrame(finalSet, columns=['companyName'])
finalCompanyDf.to_csv('finalCompanyList.csv', index=False)
finalCompanyDf

               companyName
0                    ABOBE
1                ACCENTURE
2                   ALSTOM
3             AMADEUS LABS
4                   AMAZON
..                     ...
80                   WIPRO
81  WONKSKNOW TECHNOLOGIES
82                 ZOOM RX
83                 ZSCALER
84                [24]7.AI

[85 rows x 1 columns]

In [278]:
# insert into companyData (companyName,managerId) values('CISCO ',2);

# Generate SQL insert statements from finalCompanyDf

finalCompanyDf['managerId'] = 2
finalCompanyDf

               companyName  managerId
0                    ABOBE          2
1                ACCENTURE          2
2                   ALSTOM          2
3             AMADEUS LABS          2
4                   AMAZON          2
..                     ...        ...
80                   WIPRO          2
81  WONKSKNOW TECHNOLOGIES          2
82                 ZOOM RX          2
83                 ZSCALER          2
84                [24]7.AI          2

[85 rows x 2 columns]

In [279]:
# Write insert statements to file

f = open('insertCompanyData.sql', 'w')
for index, row in finalCompanyDf.iterrows():
    f.write("insert into companyData (companyName,managerId) values('" + row['companyName'] + "'," + str(row['managerId']) + ");\n")

f.close()

In [280]:
finalCompanyDf['companyId'] = finalCompanyDf.index + 1
finalCompanyDf

               companyName  managerId  companyId
0                    ABOBE          2          1
1                ACCENTURE          2          2
2                   ALSTOM          2          3
3             AMADEUS LABS          2          4
4                   AMAZON          2          5
..                     ...        ...        ...
80                   WIPRO          2         81
81  WONKSKNOW TECHNOLOGIES          2         82
82                 ZOOM RX          2         83
83                 ZSCALER          2         84
84                [24]7.AI          2         85

[85 rows x 3 columns]

In [281]:
finalCompanyDf.to_csv('finalCompanyList.csv', index=False)

## 2024 Batch

In [282]:
df_2024 = pd.read_csv('../done/2024.csv')
df_2024

,studentEmail,studentName,studentSection,companyId,placementDate,jobLocation,jobRole,ctc,isOnCampus,studentRollNo,isIntern,isPPO,isGirlsDrive,isHigherStudies,studentDept,studentBatch,isPlaced,studentPassword
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,1,2022-10-17,Bengaluru,Technical Consultant,10.71,1,CB.EN.U4CSE20108,0,0,0,0,CSE,2024,1,cb.en.u4cse20108@cb.students.amrita.edu_B
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,2,2022-11-11,Bangalore,Advanced Application Engineering Analyst,11.89,1,CB.EN.U4CSE20121,0,0,0,0,CSE,2024,1,cb.en.u4cse20121@cb.students.amrita.edu_B
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,2,2022-11-11,Banglore,Advanced App Engineering Analyst,11.89,1,CB.EN.U4CSE20153,0,0,0,0,CSE,2024,1,cb.en.u4cse20153@cb.students.amrita.edu_B
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,2,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,11.89,1,CB.EN.U4CSE20466,0,0,0,0,CSE,2024,1,cb.en.u4cse20466@cb.students.amrita.edu_E
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,2,2023-08-24,Coimbatore,Advanced App Engineering Analyst,11.89,1,CB.EN.U4CSE20640,0,0,0,0,CSE,2024,1,cb.en.u4cse20640@cb.students.amrita.edu_F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,76,2023-09-06,Chennai,Software Engineer,9.74,1,CB.EN.U4CSE20615,0,0,0,0,CSE,2024,1,cb.en.u4cse20615@cb.students.amrita.edu_F
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,78,2023-08-25,Coimbatore,Software Engineer,7.00,1,CB.EN.U4CSE20425,0,0,0,0,CSE,2024,1,cb.en.u4cse20425@cb.students.amrita.edu_E
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,80,2023-09-15,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20051,0,0,0,0,CSE,2024,1,cb.en.u4cse20051@cb.students.amrita.edu_A
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,80,2023-09-15,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20109,0,0,0,0,CSE,2024,1,cb.en.u4cse20109@cb.students.amrita.edu_B
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,80,2023-09-25,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20348,0,0,0,0,CSE,2024,1,cb.en.u4cse20348@cb.students.amrita.edu_D

In [283]:
## Add Students and get studentId

# studentRollNo,studentEmail,studentPassword,studentName,studentSection,studentGender,studentBatch,studentDept,isHigherStudies,isPlaced,

student_df = df_2024[['studentRollNo', 'studentEmail', 'studentPassword', 'studentName', 'studentSection', 'studentBatch', 'studentDept', 'isHigherStudies', 'isPlaced']]
student_df

,studentRollNo,studentEmail,studentPassword,studentName,studentSection,studentBatch,studentDept,isHigherStudies,isPlaced
0,CB.EN.U4CSE20108,cb.en.u4cse20108@cb.students.amrita.edu,cb.en.u4cse20108@cb.students.amrita.edu_B,N.Apoorva,B,2024,CSE,0,1
1,CB.EN.U4CSE20121,cb.en.u4cse20121@cb.students.amrita.edu,cb.en.u4cse20121@cb.students.amrita.edu_B,Gadde Uday Kiran,B,2024,CSE,0,1
2,CB.EN.U4CSE20153,cb.en.u4cse20153@cb.students.amrita.edu,cb.en.u4cse20153@cb.students.amrita.edu_B,G Rama Vamsidhar Reddy,B,2024,CSE,0,1
3,CB.EN.U4CSE20466,cb.en.u4cse20466@cb.students.amrita.edu,cb.en.u4cse20466@cb.students.amrita.edu_E,T SUBHASH GUPTA,E,2024,CSE,0,1
4,CB.EN.U4CSE20640,cb.en.u4cse20640@cb.students.amrita.edu,cb.en.u4cse20640@cb.students.amrita.edu_F,Nallabantu Sri Charan,F,2024,CSE,0,1
...,...,...,...,...,...,...,...,...,...
124,CB.EN.U4CSE20615,cb.en.u4cse20615@cb.students.amrita.edu,cb.en.u4cse20615@cb.students.amrita.edu_F,Dharshita R,F,2024,CSE,0,1
125,CB.EN.U4CSE20425,cb.en.u4cse20425@cb.students.amrita.edu,cb.en.u4cse20425@cb.students.amrita.edu_E,S Jayandar,E,2024,CSE,0,1
126,CB.EN.U4CSE20051,cb.en.u4cse20051@cb.students.amrita.edu,cb.en.u4cse20051@cb.students.amrita.edu_A,Preethi Prabha,A,2024,CSE,0,1
127,CB.EN.U4CSE20109,cb.en.u4cse20109@cb.students.amrita.edu,cb.en.u4cse20109@cb.students.amrita.edu_B,Arvapalli Alekhya,B,2024,CSE,0,1
128,CB.EN.U4CSE20348,cb.en.u4cse20348@cb.students.amrita.edu,cb.en.u4cse20348@cb.students.amrita.edu_D,PRIYANKA K,D,2024,CSE,0,1

In [284]:
f = open('insertStudentData.sql', 'w')

for index, row in student_df.iterrows():
    f.write("insert into studentData (studentRollNo,studentEmail,studentPassword,studentName,studentSection,studentBatch,studentDept,isHigherStudies,isPlaced) values('" + row['studentRollNo'] + "','" + row['studentEmail'] + "','" + row['studentPassword'] + "','" + row['studentName'] + "','" + row['studentSection'] + "','" + str(row['studentBatch']) + "','" + row['studentDept'] + "'," + str(row['isHigherStudies']) + "," + str(row['isPlaced']) + ");\n")

f.close()

In [285]:
## Add studentId to df_2024 which is index + 1

df_2024['studentId'] = df_2024.index + 1
df_2024

,studentEmail,studentName,studentSection,companyId,placementDate,jobLocation,jobRole,ctc,isOnCampus,studentRollNo,isIntern,isPPO,isGirlsDrive,isHigherStudies,studentDept,studentBatch,isPlaced,studentPassword,studentId
0,cb.en.u4cse20108@cb.students.amrita.edu,N.Apoorva,B,1,2022-10-17,Bengaluru,Technical Consultant,10.71,1,CB.EN.U4CSE20108,0,0,0,0,CSE,2024,1,cb.en.u4cse20108@cb.students.amrita.edu_B,1
1,cb.en.u4cse20121@cb.students.amrita.edu,Gadde Uday Kiran,B,2,2022-11-11,Bangalore,Advanced Application Engineering Analyst,11.89,1,CB.EN.U4CSE20121,0,0,0,0,CSE,2024,1,cb.en.u4cse20121@cb.students.amrita.edu_B,2
2,cb.en.u4cse20153@cb.students.amrita.edu,G Rama Vamsidhar Reddy,B,2,2022-11-11,Banglore,Advanced App Engineering Analyst,11.89,1,CB.EN.U4CSE20153,0,0,0,0,CSE,2024,1,cb.en.u4cse20153@cb.students.amrita.edu_B,3
3,cb.en.u4cse20466@cb.students.amrita.edu,T SUBHASH GUPTA,E,2,2023-08-26,Bangalaore,Accenture Advanced Engineering Hiring,11.89,1,CB.EN.U4CSE20466,0,0,0,0,CSE,2024,1,cb.en.u4cse20466@cb.students.amrita.edu_E,4
4,cb.en.u4cse20640@cb.students.amrita.edu,Nallabantu Sri Charan,F,2,2023-08-24,Coimbatore,Advanced App Engineering Analyst,11.89,1,CB.EN.U4CSE20640,0,0,0,0,CSE,2024,1,cb.en.u4cse20640@cb.students.amrita.edu_F,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,cb.en.u4cse20615@cb.students.amrita.edu,Dharshita R,F,76,2023-09-06,Chennai,Software Engineer,9.74,1,CB.EN.U4CSE20615,0,0,0,0,CSE,2024,1,cb.en.u4cse20615@cb.students.amrita.edu_F,125
125,cb.en.u4cse20425@cb.students.amrita.edu,S Jayandar,E,78,2023-08-25,Coimbatore,Software Engineer,7.00,1,CB.EN.U4CSE20425,0,0,0,0,CSE,2024,1,cb.en.u4cse20425@cb.students.amrita.edu_E,126
126,cb.en.u4cse20051@cb.students.amrita.edu,Preethi Prabha,A,80,2023-09-15,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20051,0,0,0,0,CSE,2024,1,cb.en.u4cse20051@cb.students.amrita.edu_A,127
127,cb.en.u4cse20109@cb.students.amrita.edu,Arvapalli Alekhya,B,80,2023-09-15,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20109,0,0,0,0,CSE,2024,1,cb.en.u4cse20109@cb.students.amrita.edu_B,128
128,cb.en.u4cse20348@cb.students.amrita.edu,PRIYANKA K,D,80,2023-09-25,Bangalore,Associate Engineer,7.50,1,CB.EN.U4CSE20348,0,0,0,0,CSE,2024,1,cb.en.u4cse20348@cb.students.amrita.edu_D,129

In [286]:
# studentID,companyID,ctc,jobRole,placementDate,isIntern,isPPO,isOnCampus,isGirlsDrive

placement_df = df_2024[['studentId', 'companyId', 'ctc', 'jobRole', 'placementDate', 'isIntern', 'isPPO', 'isOnCampus', 'isGirlsDrive']]
placement_df.rename(columns={'companyId': 'companyID'}, inplace=True)
placement_df

/var/folders/79/k0pjppyx72xcfj5m7k0_zjqm0000gp/T/ipykernel_10754/4135973960.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  placement_df.rename(columns={'companyId': 'companyID'}, inplace=True)

,studentId,companyID,ctc,jobRole,placementDate,isIntern,isPPO,isOnCampus,isGirlsDrive
0,1,1,10.71,Technical Consultant,2022-10-17,0,0,1,0
1,2,2,11.89,Advanced Application Engineering Analyst,2022-11-11,0,0,1,0
2,3,2,11.89,Advanced App Engineering Analyst,2022-11-11,0,0,1,0
3,4,2,11.89,Accenture Advanced Engineering Hiring,2023-08-26,0,0,1,0
4,5,2,11.89,Advanced App Engineering Analyst,2023-08-24,0,0,1,0
...,...,...,...,...,...,...,...,...,...
124,125,76,9.74,Software Engineer,2023-09-06,0,0,1,0
125,126,78,7.00,Software Engineer,2023-08-25,0,0,1,0
126,127,80,7.50,Associate Engineer,2023-09-15,0,0,1,0
127,128,80,7.50,Associate Engineer,2023-09-15,0,0,1,0
128,129,80,7.50,Associate Engineer,2023-09-25,0,0,1,0

In [287]:
placement_df['ctc'] = placement_df['ctc'].astype(str)

/var/folders/79/k0pjppyx72xcfj5m7k0_zjqm0000gp/T/ipykernel_10754/1162703927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  placement_df['ctc'] = placement_df['ctc'].astype(str)

In [292]:
placement_df['jobRole'].fillna('NA', inplace=True)

/var/folders/79/k0pjppyx72xcfj5m7k0_zjqm0000gp/T/ipykernel_10754/2746388757.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  placement_df['jobRole'].fillna('NA', inplace=True)

In [294]:
f = open('insertPlacementData.sql', 'w')

for index, row in placement_df.iterrows():
    f.write("insert into placementData (studentId,companyID,ctc,jobRole,placementDate,isIntern,isPPO,isOnCampus,isGirlsDrive) values(" + str(row['studentId']) + "," + str(row['companyID']) + "," + str(row['ctc']) + ",'" + row['jobRole'] + "','" + str(row['placementDate']) + "'," + str(row['isIntern']) + "," + str(row['isPPO']) + "," + str(row['isOnCampus']) + "," + str(row['isGirlsDrive']) + ");\n")

f.close()